### ISSUE TITLE
Any event when two persons collide in space?

### ISSUE THREAD

**Issue by deemeetree** [Theoriz/Augmenta#2]
How is it possible to know when the two people collided in space? Is there an event for this?

**Comment by Lyptik** [comment]
No, there is no event for collision, what happens when two persons get really close is (depending on your detection and sensitivity settings) :

either the persons stays, they are just really close
either they collide into one point (then the system thinks there is just briefly one person)

That's basically a limitation of the system, you can use it to detect collision.
One way to do this is to check if somebody is disappearing or appearing in the middle of the scene, since this happens only on the border of the area. Then you can find out the two person who just did merge (collision) or separate again (separation).
You can take a look in this example, somebody did use this technic during a workshop to detect hugs and shared his example in the community here (it was working pretty well) :
https://github.com/Theoriz/AugmentaAS3
All the best,
